language: python
python:
- '3.6'
git:
  depth: 1
addons:
  sonarcloud:
    organization: pinto18-github
    token: "${SONAR_TOKEN}"
install:
- pip install -r requirements.txt
script:
- pytest --cov-report term --cov-report xml:coverage-reports/coverage-report.xml --cov=.
after_script:
- sonar-scanner
notifications:
  slack:
    rooms:
      secure: MussAlcKomoFJk3h051fMWjB2+UqejPf6UFjp+5VVaFlN8z1W/5Qqet8PQrVJ7m8QM0S2/UVEA/utwYg521k6YzUbrhzKHhm/XGicXHgO8JTGVjQOa0itS4eyxs6/+ZveGesyFkLVp7wWbyVBe/wQ7nzVZZ8MFuVMH2lmwbpNIvNQBspoTHY5dLi0R53CXgsdvZi0BqSlxpJoJeQJX+hOMu0+zXuNfwHltiWnaQCsF0AhAEGOHi2tgkjovI3bUA3q9liJygPZenASF83wKAv26TPDVDL31G4bXrOEg2n/oj9ioYTkh5wv03hiC3IKDwBkfiQVoO+dlKViK8CvQetu9K+h5uKhtsJb84Lf53D+vQAA30s0qgCiEJDUFOVCdTuLKt18zyu2svtdyuKch+NvJ8xKWlFwJMoX9cTjaR1WJa2KHBEq9928Rf5nSxL3J8pTpAMS39ihNU/H3GPB6NTLR3oMg4f2YV/dugWqx4mJUsm0tMvxjQ3kQFajRcps7Rtj7ob6zyV/s0h7K3oURw8GFNrETx0Frg1uqiVDcRyXU7FxljCnTl+yHQJxExXcfioDxVXHbHXW5nGb/Kz8SM5QWSoxC1n+TWMKpX0M/Or7RWcginrpMhWIZku7fxz7AmU5SnVucdNTpZkiohUfTiQPKQsMTcZnfyVAioRQXFItCE=
    on_success: always
    on_failure: always
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
